#!/bin/bash
# worktree をセットアップする（worktree + ブランチ作成）
# 引数: branch-name [base-branch]
# 出力: 作成した worktree のパス
# 使用例:
#   WORKTREE_PATH=$(./setup-worktree.sh feature/new-feature)
#   WORKTREE_PATH=$(./setup-worktree.sh feature/new-feature main)

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <branch-name> [base-branch]" >&2
  exit 1
fi

BRANCH_NAME="$1"
BASE_BRANCH="${2:-}"

# リポジトリルートを取得
REPO_ROOT=$(git rev-parse --show-toplevel)

# ブランチ名からworktreeディレクトリ名を生成
# スラッシュをアンダースコアに置換
WORKTREE_DIR=$(echo "${BRANCH_NAME}" | sed 's/\//_/g')
WORKTREE_PATH="${REPO_ROOT}/.worktrees/${WORKTREE_DIR}"

# worktree作成（ベースブランチ指定があればそれを使用）
if [[ -n "${BASE_BRANCH}" ]]; then
  git worktree add "${WORKTREE_PATH}" -b "${BRANCH_NAME}" "${BASE_BRANCH}"
else
  git worktree add "${WORKTREE_PATH}" -b "${BRANCH_NAME}"
fi

# .worktree.env を作成
DOCKER_WORKTREE_PATH="/worktrees/${WORKTREE_DIR}"

cat > "${WORKTREE_PATH}/.worktree.env" << EOF
# Worktree configuration
# Generated by setup-worktree.sh at $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Worktree のパス（ホスト）
WORKTREE_PATH="${WORKTREE_PATH}"

# メインリポジトリのパス
MAIN_REPO_PATH="${REPO_ROOT}"

# Docker コンテナ内の worktree パス
DOCKER_WORKTREE_PATH="${DOCKER_WORKTREE_PATH}"

# ブランチ名
BRANCH_NAME="${BRANCH_NAME}"

# Feature ID (コミット用)
FEATURE_ID="${BRANCH_NAME}"
EOF

echo "${WORKTREE_PATH}"
